# Generated by Django 5.2.17 on 2026-09-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الزيارة')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('COMPLETED', 'مكتملة')], default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('source_reference_title', models.CharField(blank=True, max_length=250, verbose_name='عنوان المرجع وقت الإنشاء')),
                ('source_reference_visibility', models.CharField(blank=True, max_length=16, verbose_name='نطاق المرجع وقت الإنشاء')),
                ('source_reference_revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='مراجعة المرجع وقت الإنشاء')),
                ('institution_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤسسة وقت الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_visits', to=settings.AUTH_USER_MODEL, verbose_name='أكملها')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='institutions.institution', verbose_name='المؤسسة')),
                ('source_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='catalog.reference', verbose_name='المرجع المصدر')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VisitNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('node_type', models.CharField(choices=[('BRANCH', 'فرع / قسم'), ('DESCRIPTION', 'وصف / مواصفة'), ('CHECKLIST_ITEM', 'بند تفتيش')], max_length=20, verbose_name='النوع')),
                ('code', models.CharField(max_length=120, verbose_name='المعرّف الثابت')),
                ('source_node_id', models.IntegerField(blank=True, null=True, verbose_name='معرّف العنصر المصدر')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='التفصيل')),
                ('value_type', models.CharField(choices=[('NONE', 'بدون قيمة'), ('TEXT', 'نص'), ('NUMBER', 'عدد'), ('DATE', 'تاريخ'), ('BOOLEAN', 'نعم / لا')], default='NONE', max_length=16, verbose_name='نوع القيمة')),
                ('position', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('origin', models.CharField(blank=True, choices=[('LEGACY', 'موروث من المرجع'), ('MANUAL', 'اختيار يدوي'), ('GUIDE', 'من دليل'), ('ASSIGNMENT', 'من تكليف'), ('LOCAL', 'محتوى محلي')], help_text='يُكتب مرة واحدة عند دخول العنصر إلى النطاق ولا يُستبدل لاحقًا. القيمة الفارغة تعني عنصر هيكلي لم يدخل النطاق.', max_length=16, null=True, verbose_name='المصدر')),
                ('is_selected', models.BooleanField(default=False, help_text='False تعني عقدة سياق فقط: تُعرض لكنها لا تدخل حساب الإنجاز.', verbose_name='داخل النطاق')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('EXCLUDED', 'مستبعد')], default='ACTIVE', max_length=16, verbose_name='الحالة')),
                ('baseline_scope_locked', models.BooleanField(default=False, verbose_name='قيد نطاق أساسي')),
                ('baseline_completion_required', models.BooleanField(default=False, verbose_name='متطلب إتمام أساسي')),
                ('result', models.CharField(blank=True, choices=[('', '—'), ('MATCH', 'مطابق'), ('NOT_MATCH', 'غير مطابق'), ('NOT_APPLICABLE', 'غير منطبق')], default='', max_length=16, verbose_name='النتيجة')),
                ('observation', models.TextField(blank=True, verbose_name='ملاحظة / مشاهدة')),
                ('value_text', models.TextField(blank=True, verbose_name='قيمة نصية')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='قيمة عددية')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='قيمة تاريخ')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='قيمة منطقية')),
                ('excluded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستبعاد')),
                ('excluded_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_descendants', to='visits.visitnode', verbose_name='استُبعد ضمن')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='visits.visitnode', verbose_name='العقدة الأم')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'عنصر زيارة',
                'verbose_name_plural': 'عناصر الزيارة',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['inspector', 'status'], name='visits_visi_inspect_0b3a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['institution', 'visit_date'], name='visits_visi_institu_ced256_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('completed_at__isnull', False), _connector='OR'), name='completed_visit_has_completed_at'),
        ),
        migrations.AddIndex(
            model_name='visitnode',
            index=models.Index(fields=['visit', 'status', 'is_selected'], name='visits_visi_visit_i_969c78_idx'),
        ),
        migrations.AddIndex(
            model_name='visitnode',
            index=models.Index(fields=['visit', 'parent', 'position'], name='visits_visi_visit_i_76fcce_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.UniqueConstraint(fields=('visit', 'code'), name='unique_visit_node_code'),
        ),
        migrations.AddConstraint(
            model_name='visitnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('excluded_at__isnull', False), ('status', 'EXCLUDED')), ('status', 'ACTIVE'), _connector='OR'), name='excluded_node_has_timestamp'),
        ),
    ]
