# Generated by Django 5.2.17 on 2026-09-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان التكليف')),
                ('instruction', models.TextField(blank=True, verbose_name='نص التكليف')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة إدارية'), ('ISSUED', 'صادر'), ('REVOKED', 'ملغى')], default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أصدره')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_assignments', to=settings.AUTH_USER_MODEL, verbose_name='ألغاه')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'تكليف',
                'verbose_name_plural': 'التكليفات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('scope_locked', models.BooleanField(default=False, verbose_name='قيد النطاق')),
                ('completion_required', models.BooleanField(default=False, verbose_name='متطلب إتمام')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة التكليف')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='governance.assignment', verbose_name='التكليف')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_entries', to='visits.visitnode', verbose_name='العنصر المستهدف')),
            ],
            options={
                'verbose_name': 'بند تكليف',
                'verbose_name_plural': 'بنود التكليف',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الدليل')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدليل')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=16, verbose_name='الحالة')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guides', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='catalog.reference', verbose_name='المرجع المشترك')),
            ],
            options={
                'verbose_name': 'دليل',
                'verbose_name_plural': 'الأدلة',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('guide_title_snapshot', models.CharField(max_length=250, verbose_name='عنوان الدليل وقت التطبيق')),
                ('guide_version_snapshot', models.PositiveIntegerField(default=1, verbose_name='إصدار الدليل وقت التطبيق')),
                ('added_count', models.PositiveIntegerField(default=0, verbose_name='عدد العناصر المضافة')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='عدد العناصر المتخطاة')),
                ('skipped_codes', models.JSONField(blank=True, default=list, verbose_name='معرّفات متخطاة')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_applications', to=settings.AUTH_USER_MODEL, verbose_name='طبّقه')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='governance.guide', verbose_name='الدليل')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_applications', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'تطبيق دليل',
                'verbose_name_plural': 'تطبيقات الأدلة',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GuideTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('code', models.CharField(max_length=120, verbose_name='معرّف العنصر')),
                ('title_snapshot', models.CharField(max_length=300, verbose_name='عنوان وقت الإضافة')),
                ('node_type_snapshot', models.CharField(choices=[('BRANCH', 'فرع / قسم'), ('DESCRIPTION', 'وصف / مواصفة'), ('CHECKLIST_ITEM', 'بند تفتيش')], max_length=20, verbose_name='نوع وقت الإضافة')),
                ('position', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='governance.guide', verbose_name='الدليل')),
            ],
            options={
                'verbose_name': 'عنصر دليل',
                'verbose_name_plural': 'عناصر الدليل',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['visit', 'status'], name='governance__visit_i_7af9b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('issued_at__isnull', False), _connector='OR'), name='non_draft_assignment_has_issued_at'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVOKED'), _negated=True), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False)), _connector='OR'), name='revoked_assignment_has_audit'),
        ),
        migrations.AddConstraint(
            model_name='assignmententry',
            constraint=models.UniqueConstraint(fields=('assignment', 'target_node'), name='unique_assignment_entry_target'),
        ),
        migrations.AddConstraint(
            model_name='assignmententry',
            constraint=models.CheckConstraint(condition=models.Q(('scope_locked', True), ('completion_required', True), _connector='OR'), name='assignment_entry_imposes_something'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.UniqueConstraint(fields=('reference', 'title'), name='unique_guide_title_per_reference'),
        ),
        migrations.AddConstraint(
            model_name='guideapplication',
            constraint=models.UniqueConstraint(fields=('visit', 'guide'), name='unique_guide_application_per_visit'),
        ),
        migrations.AddConstraint(
            model_name='guidetarget',
            constraint=models.UniqueConstraint(fields=('guide', 'code'), name='unique_guide_target_code'),
        ),
    ]
