# Generated by Django 5.2.17 on 2026-09-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('visibility', models.CharField(choices=[('SHARED', 'مرجع مشترك'), ('PRIVATE', 'مرجع خاص')], default='SHARED', max_length=16, verbose_name='النطاق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='المراجعة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_references', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_references', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مرجع تفتيش',
                'verbose_name_plural': 'مراجع التفتيش',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('node_type', models.CharField(choices=[('BRANCH', 'فرع / قسم'), ('DESCRIPTION', 'وصف / مواصفة'), ('CHECKLIST_ITEM', 'بند تفتيش')], max_length=20, verbose_name='النوع')),
                ('code', models.CharField(max_length=120, verbose_name='المعرّف الثابت')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='التفصيل')),
                ('value_type', models.CharField(choices=[('NONE', 'بدون قيمة'), ('TEXT', 'نص'), ('NUMBER', 'عدد'), ('DATE', 'تاريخ'), ('BOOLEAN', 'نعم / لا')], default='NONE', max_length=16, verbose_name='نوع القيمة')),
                ('is_mandatory', models.BooleanField(default=False, help_text='يمثل قيدًا أساسيًا يورَّث إلى الزيارة كمتطلب إتمام.', verbose_name='إلزامي في المرجع')),
                ('is_scope_locked', models.BooleanField(default=False, help_text='يمنع إخراج العنصر (أو أبنائه) من نطاق الزيارة.', verbose_name='مقيد النطاق في المرجع')),
                ('position', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.referencenode', verbose_name='العقدة الأم')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='catalog.reference', verbose_name='المرجع')),
            ],
            options={
                'verbose_name': 'عنصر مرجع',
                'verbose_name_plural': 'عناصر المرجع',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=16, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة المفتش')),
                ('snapshot', models.JSONField(verbose_name='لقطة المحتوى المقترح')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_note', models.TextField(blank=True, verbose_name='ملاحظة المراجعة')),
                ('approved_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_from_submission', to='catalog.reference', verbose_name='المرجع المشترك الناتج')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='catalog.reference', verbose_name='المرجع الخاص')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_submissions', to=settings.AUTH_USER_MODEL, verbose_name='قدّمه')),
            ],
            options={
                'verbose_name': 'مقترح تعميم مرجع',
                'verbose_name_plural': 'مقترحات تعميم المراجع',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.CheckConstraint(condition=models.Q(('visibility', 'SHARED'), ('owner__isnull', False), _connector='OR'), name='private_reference_requires_owner'),
        ),
        migrations.AddIndex(
            model_name='referencenode',
            index=models.Index(fields=['reference', 'parent', 'position'], name='catalog_ref_referen_b74b96_idx'),
        ),
        migrations.AddConstraint(
            model_name='referencenode',
            constraint=models.UniqueConstraint(fields=('reference', 'code'), name='unique_node_code_per_reference'),
        ),
        migrations.AddIndex(
            model_name='referencesubmission',
            index=models.Index(fields=['status', 'created_at'], name='catalog_ref_status_f1aefa_idx'),
        ),
    ]
