# Generated by Django 5.2.17 on 2026-09-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='الرمز التعريفي')),
                ('kind', models.CharField(choices=[('TRAINING_CENTER', 'مركز تكوين مهني'), ('APPRENTICESHIP', 'مركز تكوين عن طريق التمهين'), ('VOCATIONAL_SCHOOL', 'مدرسة مهنية'), ('OTHER', 'أخرى')], default='TRAINING_CENTER', max_length=32, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_institution_name_code')],
            },
        ),
    ]
